### ISSUE TITLE
BAM files cannot be opened

### ISSUE THREAD

**Issue by JulianSpagnuolo** [compbiocore/RSeqAn#1]
I'm starting to write a small script to parse some BAM records, however the function below (its the example given by the SeqAn documentation) cannot open BAM files, however SAM files are not an issue.

It's likely caused by the zlib library not being correctly linked with RSeqAn, which is present in the R libraries so I'm not sure how to fix this. Any help would be very much appreciated.

```
#include <iostream>
#include <fstream>
#include <regex>
#include <seqan/bam_io.h>

#include <Rcpp.h>

// [[Rcpp::depends(BH)]]
// [[Rcpp::depends(RSeqAn)]]
using namespace Rcpp;
using namespace seqan;


// [[Rcpp::plugins(cpp14)]]

// [[Rcpp::export]]
int bamparse(std::string bamFileName, std::string bamO) {
  
  seqan::String<char> bamFI = bamFileName;
  
  // Open input file, BamFileIn can read SAM and BAM files.
  seqan::BamFileIn bamFileIn;
  
  
  if (!open(bamFileIn, toCString(bamFI)))
  {
    std::cerr << "ERROR: Could not open " << bamFileName << std::endl;
    return 1;
  }
  // Open output file, BamFileOut accepts also an ostream and a format tag.
  //BamFileOut bamFileOut(context(bamFileIn), std::cout, Sam());
  
  try
  {
    // Copy header.
    BamHeader header;
    readHeader(header, bamFileIn);
    //writeHeader(bamFileOut, header);
    
    // Copy records.
    BamAlignmentRecord record;
    while (!atEnd(bamFileIn))
    {
      readRecord(record, bamFileIn);
      Rcpp::Rcout << toCString(record.seq) << std::endl;
      //writeRecord(bamFileOut, record);
    }
  }
  catch (Exception const & e)
  {
    std::cout << "ERROR: " << e.what() << std::endl;
    return 1;
  }
  
  return 0;
}
```

**Comment by aguang** [comment]
apologies for only replying now, for some reason I didn't get a notification about this. I will look into it and get back to you.

**Comment by aguang** [comment]
@JulianSpagnuolo the error is due to zlib not being enabled for SeqAn by default. (as well as bzip2 if you will be needing that) See their section on [preprocessor defines](https://seqan.readthedocs.io/en/master/Infrastructure/Use/CustomBuildSystem.html#seqan-has-zlib) as well as seqan/seqan#2056. I am not sure how you were running your code but either `Sys.setenv("PKG_CXXFLAGS"="-DSEQAN_HAS_ZLIB")` or setting it in Makevars should do it. Let me know if that works for you. I am planning to make a vignette describing how to link and configure RSeqAn that should clarify things like this.
